exclude:
- CNAME
- Gemfile
- Gemfile.lock
- btc.gemspec
- scripts/spreadsheet_to_resource_mds/

plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-postfiles

include: ['_pages']

sass:
  add_charset: true
  excerpt_separator: <!-- more -->
  permalink: pretty
  sass_dir: assets/sass
  style: compressed
  timezone: Europe/London

collections_dir: collections
collections:
  posts:
    title: Posts
    output: true
  authors:
    title: Authors
    permalink: /authors/
    output: true
  projects_and_companies:
    title: Projects and Companies
    output: true
    permalink: /projects_and_companies/
  multimedia:
    title: Multimedia
    output: true
    permalink: /multimedia/
  writings:
    title: Writings
    output: true
    permalink: /writings/

defaults:
  - scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /authors/:slug/
  - scope:
      path: ""
      type: writings
    values:
      layout: writing
      permalink: /writings/:title/
  - scope:
      path: ""
      type: multimedia
    values:
      layout: media
      permalink: /multimedia/:title/

encoding: utf-8
lang: en-US
title: "Bitcoin Rabbit Hole"
# logo: "/assets/logo.svg"
description: "Bitcoin Rabbit Hole"
url: ""
baseurl: ""
email: "adamtache@gmail.com"
# avatarurl: TODO
css_inline: true

navigation_footer:
  BTC:

menu_items:
  Home: /
  Essays & Research: /writings/
  Multimedia: /multimedia/
  Projects & Companies: /projects_and_companies/
  Blog: /blog/

social_links:
  Twitter: https://twitter.com/adam_tache
  GitHub: https://github.com/adamtache
  RSS: /feed.xml

sharing_links:
  Twitter: "#0d94e7"
  Hacker News: "#ff6600"
